name         'stdmod-redis'
version      '0.0.1'
author       'Stdmod authors'
license      'Apache2'
project_page 'https://github.com/stdmod'
source       'https://github.com/stdmod/puppet-redis'
summary      'Puppet module for redis'
description  'This module installs and manages redis. Check README for details.'
dependency   'puppetlabs/stdlib', '>=2.0.0'
